name: diff_match_atch
description: Evaluate the health and quality of a Dart package
version: 0.19.0-dev
homepage: https://github.com/google/diff-match-patch/tree/master/dart

environment:
  sdk: '>=2.12.0 <3.0.0'